### ISSUE TITLE
get doesn't appear to work in cljs repl

### ISSUE THREAD

**Issue by joinr** [helins/interval.cljc#1]
;;[io.helins/interval "1.0.0-beta0"]

```clojure
(require '[helins.interval.map :as imap])

user> (def im (-> imap/empty (imap/mark 1 2 [:hello]) (imap/mark 3 10 [:world]) (imap/mark 11 11 [:end])))
#'user/im
user> im
{[1 2] #{[:hello]}, [3 10] #{[:world]}, [11 11] #{[:end]}}
user> (get im 2)
nil

user> im
{[1 2] #{[:hello]}, [3 10] #{[:world]}, [11 11] #{[:end]}}
```

Tested from a browser repl.

**Comment by helins** [comment]
This is odd, tests pass and I have used this library extensively in browser CLJS apps without never having a problem.

What is your setup? Did you encounter this in any different context?

**Comment by joinr** [comment]
>What is your setup? Did you encounter this in any different context?

I was in a project https://github.com/joinr/cesiumdemo/tree/figmain connected to the browser through spacemacs, cider, and figwheel-main.  The datastructure acted fine otherwise.  The behavior was from firefox.  Regular CLJ repl works fine. 

The only thought I have is that it's possible if there is any associated pretty printing of the values (doubtful), that cider's default to pretty printing is messing with something (I've seen this with defrecord behavior and custom types, having to implement pretty-print).  I will try an isolated project and maybe mess with different browsers.

**Comment by joinr** [comment]
Looks like the main example works:

```clojure
cljs.user> (require '[helins.interval.map :as imap])
cljs.user> (def music
     (-> imap/empty
         ;; Broken C minor chord.
         (imap/mark  0  8 :c)
         (imap/mark  3  8 :e-flat)
         (imap/mark  5  8 :g)
         ;; After a pause, G is repeated.
         (imap/mark 10 11 :g)))
#'cljs.user/music
cljs.user> (get music 4)
#{:c :e-flat}
```

**Comment by joinr** [comment]
```clojure
cljs.user> (def im (-> imap/empty (imap/mark 1 2 :hello) (imap/mark 3 10 :world) (imap/mark 11 11 :end)))
#'cljs.user/im
cljs.user> (get im 4)
#{:world}
```
Looks like you cannot supply arbitrary values for the map.  At least, supplying a vector in this case yields nil for queries.

Ah never mind, getting values at 2 still fails:

```clojure
cljs.user> (get im 2)
nil

cljs.user> (get im 1)
#{:hello}
cljs.user
```

I thought the semantics were meant to be that the segment was inclusive.  Indeed, this is not the case:

```clojure
cljs.user> (get music 11)
nil
```

This leads to defining infinitesimal offsets to delineate the segments, like 2.0001 instead of 2, which is a work around.  I didn't infer that from the readme.

**Comment by helins** [comment]
Right, I didn't notice you were query on a boundary in the original post.

Indeed, an interval starts at A (inclusive) and ends at B (exclusive). There were a few reasons behind it: this is what you usually see in such libraries, it made sense implementation-wise , and it avoids confusion.

Eg. suppose `[2 5]` and `[5 7]` : surely contiguous, but don't look like they overlap, right? If end is exclusive (like in this lib), they effectively don't. If end is inclusive, they effectively do. It wouldn't be a nice property to have mathematically speaking and usually in computer science you'll observe that ends are often exclusive.

However I would be interested in knowing more if you have use cases where end being inclusive is a must. Personally, I have always preferred it to be exclusive.

Let me know if this is a satisfactory enough answer for closing this issue :)

**Comment by joinr** [comment]
The semantics fit fine with e.g. `clojure.core/range` which is exclusive.  It's just not documented explicitly.  I think I have seen other implementations where the interval is inclusive....although I am far from an expert.  Boundary conditions are definitely a concern.  I would say in spatial relationships, I would definitely assume [2 5] and [5 7] have an overlap at 5, where [2 5] and [6 7] do not, or [2 5] and [5.000000001 7] do not.  These are basic discrete signal sampling problems I think; as long as the semantics are clear, it's easy to paper over them.  Callers can establish the desired semantics e.g. by wrapping `mark`, e.g. 

```clojure
(mark-inclusive imap 2 5 :some-value) === (mark imap 2 (inc 5) :some-value)
(mark-inclusive imap 2 5 :some-value 1e-6)  === (mark imap 2 (+ 5 1e-6) :some-value)
```

**Comment by helins** [comment]
You are quite right, I'll mention it in the README.

Thanks for the feedback!
